export const URL='http://elife.hk0472.com';//'http://192.168.1.240:8080'//'http://api.hk0472.com/';//
export const CategoryUrl=URL+'/goods/mobcates';
export const SuggestionUrl=URL+'/suggestions/completion?size=10&queryString=';
export const SearchUrl=URL+'/search/goods';
export const FilterUrl=URL+'/search/goods/aggregations';
export const AddressUrl=URL+'/area/all';
export const DetailUrl=URL+'/goods/';
export const AreaUrl=URL+'/area/defaultArea';
export const LoginUrl=URL+'/customer/login';